/* verify_parity.mjs — self-contained rapp/1 parity gate.
 *
 * The mandatory gate compares the shipped JavaScript implementation with
 * committed vectors generated by kody-w/rapp-1 at the exact commit recorded in
 * rapp-1-reference-vectors.json. It never requires Python, HOME, or another
 * checkout.
 *
 *   node verify_parity.mjs
 *   node verify_parity.mjs --external[=/path/to/rapp-1]  # optional cross-check
 *   node verify_parity.mjs --mutate-result               # must exit nonzero
 *   node verify_parity.mjs --mutate-expected             # must exit nonzero
 *   node verify_parity.mjs --mutate-nexus                # must exit nonzero
 *   node verify_parity.mjs --mutate-arena                # must exit nonzero
 */
import { readFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const vectorPath = join(here, 'rapp-1-reference-vectors.json');
const vectors = JSON.parse(readFileSync(vectorPath, 'utf8'));
const REQUIRED_METADATA = {
  format: 'rapp/1-reference-vectors/1',
  source_repository: 'https://github.com/kody-w/rapp-1',
  source_commit: '67dacce4f8ce5909aa1fd6dd401d0f8183d730a8',
  reference_implementation: 'rapp.py',
  specification: 'SPEC.md',
  spec_revision: 'rev-6',
};

const metadataProblems = [];
if (vectors.format !== REQUIRED_METADATA.format) metadataProblems.push('vector format');
for (const [key, expected] of Object.entries(REQUIRED_METADATA)) {
  if (key === 'format') continue;
  if (vectors.metadata?.[key] !== expected) metadataProblems.push('metadata.' + key);
}
if (!vectors.cases || typeof vectors.cases !== 'object' || !Object.keys(vectors.cases).length) {
  metadataProblems.push('cases');
}
if (metadataProblems.length) {
  console.error('pinned vector file is invalid: ' + metadataProblems.join(', '));
  process.exit(2);
}

/* ── execute every shipped rapp/1 implementation independently ────────────── */
const SHIPPED = [
  { id: 'index', label: 'Workroom board', file: 'index.html' },
  { id: 'broadcast', label: 'Broadcast studio', file: 'broadcast.html' },
  { id: 'nexus', label: 'Nexus 3D', file: 'nexus3d.html' },
  { id: 'arena', label: 'Frame Arena', file: 'arena.html' },
];
const START_MARKER = '/* ── §4 canonicalization';
const END_MARKER = 'async function sha256Plain';

function extractPrimitives(file) {
  const html = readFileSync(join(here, file), 'utf8');
  const start = html.indexOf(START_MARKER);
  const end = html.indexOf(END_MARKER, start);
  if (start < 0 || end < 0 || end <= start) {
    throw new Error('could not find canonical/H primitives in ' + file);
  }
  return html.slice(start, end);
}

const blocks = {};
try {
  for (const implementation of SHIPPED) blocks[implementation.id] = extractPrimitives(implementation.file);
} catch (error) {
  console.error(error.message);
  process.exit(2);
}

/* Mutation modes alter extracted source before it is executed, proving that a
   broken Nexus or Arena implementation reaches the mandatory vector gate. */
for (const id of ['nexus', 'arena']) {
  if (!process.argv.includes('--mutate-' + id)) continue;
  const original = "enc.encode(space + '\\n')";
  if (!blocks[id].includes(original)) {
    console.error('could not apply ' + id + ' mutation: hash pre-image expression moved');
    process.exit(2);
  }
  blocks[id] = blocks[id].replace(original, "enc.encode(space + ':BROKEN\\n')");
  console.log('  mutation:          broke the extracted ' + id + ' H() primitive; the gate must fail');
}

console.log('  pinned reference:  ' + vectors.metadata.source_repository);
console.log('  source commit:     ' + vectors.metadata.source_commit);
console.log('  specification:     ' + vectors.metadata.specification + ' ' + vectors.metadata.spec_revision + '\n');

const results = {};
for (const implementation of SHIPPED) {
  const source = blocks[implementation.id]
    + '\nexport { canonical, H, Hb };\n//# sourceURL=parity-' + implementation.id + '.mjs';
  let mod;
  try {
    mod = await import('data:text/javascript,' + encodeURIComponent(source));
  } catch (error) {
    console.error(implementation.file + ' primitives could not execute: ' + error.message);
    process.exit(2);
  }
  const actual = {};
  for (const [name, vector] of Object.entries(vectors.cases)) {
    actual[name] = {
      canonical: mod.canonical(vector.input),
      particle: await mod.H('rapp/1:particle', vector.input),
      wave: await mod.H('rapp/1:wave', vector.input),
    };
  }
  results[implementation.id] = actual;
}

if (process.argv.includes('--mutate-expected')) {
  const first = Object.keys(vectors.cases)[0];
  const value = vectors.cases[first].expected.wave;
  vectors.cases[first].expected.wave = (value[0] === '0' ? '1' : '0') + value.slice(1);
  console.log('  mutation:          changed pinned ' + first + '.wave in memory; the gate must fail\n');
}
if (process.argv.includes('--mutate-result')) {
  const first = Object.keys(results.index)[0];
  results.index[first].particle =
    (results.index[first].particle[0] === '0' ? '1' : '0') + results.index[first].particle.slice(1);
  console.log('  mutation:          changed index.' + first + '.particle; the gate must fail\n');
}

function compare(results, expectedCases, label, print = true) {
  let bad = 0;
  const pad = (s, n) => s + ' '.repeat(Math.max(0, n - s.length));
  if (print) console.log(label + '\ncase          canonical  particle  wave');
  for (const [name, vector] of Object.entries(expectedCases)) {
    const a = results[name];
    const b = vector.expected;
    const c = !!a && a.canonical === b.canonical;
    const p = !!a && a.particle === b.particle;
    const w = !!a && a.wave === b.wave;
    if (!c || !p || !w) bad++;
    if (print) {
      console.log('  ' + pad(name, 12) + '  ' + pad(c ? 'same' : 'DIFFERS', 9)
                + '  ' + pad(p ? 'same' : 'DIFFERS', 8) + '  ' + (w ? 'same' : 'DIFFERS'));
      if (!c && a) {
        console.log('      got: ' + a.canonical);
        console.log('      exp: ' + b.canonical);
      }
    }
  }
  return bad;
}

let bad = 0;
const indexBlock = blocks.index;
for (const implementation of SHIPPED) {
  const actual = results[implementation.id];
  console.log('implementation: ' + implementation.label + ' (' + implementation.file + ')');
  if (blocks[implementation.id] !== indexBlock) {
    console.log('  source block: DRIFTED from index.html');
    bad++;
  } else {
    console.log('  source block: byte-identical to index.html');
  }
  bad += compare(actual, vectors.cases, '  mandatory pinned-vector gate');
  if (actual.unsorted?.particle !== actual.sorted?.particle) {
    console.log('  key ordering: DIFFERS — JCS sorting is not being applied\n');
    bad++;
  } else {
    console.log('  key ordering: identical across source key order\n');
  }
}

/* Prove the gate is independently sensitive to broken Nexus and Arena output,
   even when their checked-in implementations are currently identical. */
for (const id of ['nexus', 'arena']) {
  const probe = structuredClone(results[id]);
  const probeName = Object.keys(probe)[0];
  probe[probeName].wave = (probe[probeName].wave[0] === '0' ? '1' : '0') + probe[probeName].wave.slice(1);
  if (compare(probe, vectors.cases, id + ' mutation probe', false) === 0) {
    console.error('mutation sensitivity failed — changed ' + id + ' output was accepted');
    bad++;
  } else {
    console.log('  mutation sensitivity: broken ' + id + ' output is rejected');
  }
}

/* ── optional live Python cross-check, only when explicitly requested ─────── */
const externalArg = process.argv.find(arg => arg === '--external' || arg.startsWith('--external='));
if (externalArg) {
  const explicitPath = externalArg.includes('=') ? externalArg.slice(externalArg.indexOf('=') + 1) : '';
  const fallback = process.env.HOME ? join(process.env.HOME, 'Documents/GitHub/rapp-1') : '';
  const rapp1 = explicitPath || process.env.RAPP1_DIR || fallback;
  if (!rapp1) {
    console.error('\n--external requested, but no path was supplied and HOME/RAPP1_DIR is unavailable');
    process.exit(2);
  }
  const python = `
import json, sys, importlib.util
spec = importlib.util.spec_from_file_location("rapp", ${JSON.stringify(join(rapp1, 'rapp.py'))})
rapp = importlib.util.module_from_spec(spec); spec.loader.exec_module(rapp)
cases = json.load(sys.stdin)
out = {}
for name, v in cases.items():
    out[name] = { "canonical": rapp.canonical(v),
                  "particle": rapp.H("rapp/1:particle", v),
                  "wave":     rapp.H("rapp/1:wave", v) }
print(json.dumps(out))
`;
  let reference;
  try {
    const inputs = Object.fromEntries(Object.entries(vectors.cases).map(([name, vector]) => [name, vector.input]));
    reference = JSON.parse(execFileSync('python3', ['-c', python], {
      encoding: 'utf8',
      input: JSON.stringify(inputs),
    }));
  } catch (error) {
    console.error('\nexternal reference failed at ' + rapp1);
    console.error(String(error.stderr || error.message).split('\n').slice(0, 4).join('\n'));
    process.exit(2);
  }
  bad += compare(reference, vectors.cases, '\noptional external-reference cross-check');
}

console.log(bad
  ? `\n${bad} case(s) disagree with the pinned reference — this is NOT rapp/1`
  : '\nevery case agrees with the committed rapp/1 reference vectors, byte for byte');
process.exit(bad ? 1 : 0);
